[daemon]
api_key = "ff9d0dd64490307e5d9f21db8f4677d3270df3ada29fa4937ea5db8db020e7e2"

[network.utp]
max_retransmits = 15
max_rate = 2000000
ack_interval = 0.2
retransmit_timeout_factor = 5.0
mtu = 1500
connection_timeout = 45.0
prefer_over_tcp = false
max_window_size = 65535
initial_rate = 2000
min_rate = 1024
