"""Emit ccbt/i18n/locale_data/es_val_3.json (manual Spanish, order matches dev/es_slice_3.json)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ccbt/i18n/locale_data/es_val_3.json"

V = [
    "Tamaño total",
    "Subida total",
    "Trozos totales: {count}",
    "Consultas totales",
    "Tracker",
    "Error de tracker",
    "Tracker añadido: {url}",
    "Intervalo de announce del tracker (s)",
    "Tracker quitado: {url}",
    "Intervalo de scrape del tracker (s)",
    "Trackers",
    "Siguiendo {count} torrent(s) en una ventana de {minutes} minuto(s)",
    "Tendencia: {trend} ({delta:+.1f}pp)",
    "Intervalo de actualización de la UI: {interval}s",
    "URL",
    "No disponible",
    "Intervalo de unchoke (s)",
    "Error inesperado al comprobar el estado del demonio en %s: %s",
    "Error desconocido",
    "Operación desconocida «{operation}» solicitada pero existe archivo PID del demonio. No debería ocurrir; repórtelo como error.",
    "Operación desconocida: %s",
    "Ilimitado",
    "Subida (B/s)",
    "Actualizado a las {time}",
    "Archivo de configuración actualizado con la del demonio",
    "Límite de subida",
    "Límite de subida (KiB/s):",
    "Tasa de subida",
    "Límite de tasa de subida (bytes/s, 0 = ilimitado):",
    "Límite de subida (KiB/s, 0 = ilimitado)",
    "Subida:",
    "Subido",
    "Subiendo",
    "Tiempo en marcha",
    "Uso",
    "Uso: config [show|get|set|reload] ...\nShell: btbt config describe | apply | import | schema",
    "Uso: disk [show|stats|config <key> <value>|monitor]",
    "Uso: network [show|stats|config <key> <value>|optimize|monitor]",
    "Use «btbt daemon restart» o reinicie el demonio manualmente.",
    "Use --confirm para continuar con la restauración",
    "Use --force para forzar la terminación",
    "Usar solo protocolo v2 (desactivar v1)",
    "Usar asignación en memoria (mmap)",
    "Usando puerto IPC %d de la configuración principal",
    "Usando archivo de configuración del demonio: puerto=%d, api_key_present=%s",
    "Usando ejecutor del demonio para el comando magnet",
    "Usando puerto IPC predeterminado %d (puede no existir el archivo de config. del demonio)",
    "Mediana de utilización",
    "Rango de utilización",
    "Muestras de utilización",
    "Generación de torrent v1 aún no implementada",
    "VS Code oscuro",
    "Validar solo la superposición del archivo fusionado; no escribir",
    "Solo validar; no escribir el archivo de configuración",
    "Error de validación: %s",
    "Valor a establecer (útil para cadenas con espacios o JSON); sobrescribe VALUE posicional",
    "Verificación completada: {verified} correctos, {failed} fallidos de {total}",
    "Verificación fallida: {error}",
    "Verificar archivos",
    "Visual",
    "Esperar metadatos",
    "Esperar metadatos y solicitar selección de archivos (solo interactivo)",
    "Advertencias:",
    "Error WebSocket en recepción por lotes: %s",
    "Error WebSocket: %s",
    "Error en bucle de recepción WebSocket: %s",
    "WebTorrent",
    "Tamaño de lista blanca",
    "Pares en lista blanca",
    "Error específico de Windows al comprobar el demonio (os.kill()): %s — no hay archivo PID; se creará sesión local",
    "Tiempo de espera de lote de escritura",
    "Tamaño de lote de escritura (KiB)",
    "Tamaño de búfer de escritura (KiB)",
    "Escribir configuración fusionada en el archivo global",
    "Escribir configuración fusionada en ccbt.toml local del proyecto",
    "Caché de write-back",
    "Escribiendo archivo de exportación...",
    "Catálogo escrito en {path}",
    "Carpetas XET",
    "Opciones del protocolo Xet:\n\nXet permite trozos definidos por contenido y deduplicación.\nÚtil para reducir almacenamiento al descargar contenido similar.",
    "Gestión Xet",
    "Puede omitir la espera y continuar con todos los archivos seleccionados.",
    "Recuento de estado cero",
    "[blue]Progreso: {verified}/{total} piezas verificadas[/blue]",
    "[blue]Ejecutando: {command}[/blue]",
    "[bold green]Enlace para compartir:[/bold green]",
    "[bold]Alias ({count}):[/bold]\n",
    "[bold]Lista permitida ({count} pares):[/bold]\n",
    "[bold]Configuración:[/bold]",
    "[bold]Descubriendo dispositivos NAT...[/bold]\n",
    "[bold]Asignando puerto {protocol} {port}...[/bold]",
    "[bold]Estado de NAT traversal[/bold]\n",
    "[bold]Quitando asignación de puerto {protocol} para puerto {port}...[/bold]",
    "[bold]Modo de sincronización para: {path}[/bold]\n",
    "[bold]Estado de sincronización para: {path}[/bold]\n",
    "[bold]Información de caché Xet[/bold]\n",
    "[bold]Estadísticas de caché de deduplicación Xet[/bold]\n",
    "[bold]Estado del protocolo Xet[/bold]\n",
    "[cyan]Comprobando si ya hay una instancia del demonio...[/cyan]",
    "[cyan]Creando torrent {format}...[/cyan]",
    "[cyan]Descarga:[/cyan] {rate:.2f} KiB/s",
    "[cyan]Inicializando configuración...[/cyan]",
    "[cyan]Cargando filtro desde: {file_path}[/cyan]",
    "[cyan]Reiniciando demonio...[/cyan]",
    "[cyan]Ejecutando comprobaciones de diagnóstico...[/cyan]\n",
    "[cyan]Iniciando demonio en segundo plano...[/cyan]",
    "[cyan]Iniciando demonio en primer plano...[/cyan]",
    "[cyan]Probando conexión al proxy {host}:{port}...[/cyan]",
    "[cyan]Torrents:[/cyan] {num_torrents}",
    "[cyan]Actualizando listas de filtro desde {count} URL(s)...[/cyan]",
    "[cyan]Subida:[/cyan] {rate:.2f} KiB/s",
    "[cyan]Tiempo en marcha:[/cyan] {uptime:.1f}s",
    "[cyan]Usando puerto IPC personalizado: {port}[/cyan]",
    "[cyan]Esperando a que el demonio esté listo...[/cyan]",
    "[dim]  uv run btbt daemon start --foreground[/dim]",
    "[dim]El demonio puede seguir iniciándose. Use «btbt daemon status» para comprobar.[/dim]",
    "[dim]Info hash v1 (SHA-1): {hash}...[/dim]",
    "[dim]Info hash v2 (SHA-256): {hash}...[/dim]",
    "[dim]Sin asignaciones de puerto activas[/dim]",
    "[dim]Salida: {path}[/dim]",
    "[dim]Reinicie manualmente: «btbt daemon restart»[/dim]",
    "[dim]Reinicie el demonio manualmente: «btbt daemon restart»[/dim]",
    "[dim]Protocolo: {method}[/dim]",
    "[dim]Vea el registro del demonio: {path}[/dim]",
    "[dim]Origen: {path}[/dim]",
    "[dim]Trackers: {count}[/dim]",
    "[dim]Intente con la opción --foreground para ver el error detallado:[/dim]",
    "[dim]Use «btbt daemon status» para el estado del demonio[/dim]",
    "[dim]Use -v para más detalles o revise los registros del demonio[/dim]",
    "[dim]Web seeds: {count}[/dim]",
    "[green]PERMITIDO[/green]",
    "[green]Protocolo activo:[/green] {method}",
    "[green]Regla de alerta {name} añadida[/green]",
    "[green]Añadido a IPFS:[/green] {cid}",
    "[green]Aplicando optimizaciones {preset}...[/green]",
    "[green]Resultados de benchmark:[/green] {results}",
    "[green]Ruta de certificados CA establecida en {path}. Configuración guardada en {config_file}[/green]",
    "[green]Punto de control para {hash} es válido[/green]",
    "[green]Punto de control para {info_hash} es válido[/green]",
    "[green]Punto de control actualizado para {hash}[/green]",
    "[green]Punto de control recargado para {hash}[/green]",
    "[green]Punto de control guardado para el torrent[/green]",
    "[green]Punto de control guardado[/green]",
    "[green]Punto de control válido[/green]",
    "[green]Se borraron todas las alertas activas[/green]",
    "[green]Cola vaciada[/green]",
    "[green]Certificado de cliente establecido. Configuración guardada en {config_file}[/green]",
    "[green]Conectado al demonio[/green]",
    "[green]Contenido fijado[/green]",
    "[green]Contenido guardado en:[/green] {output}",
    "[green]Modo DHT agresivo {mode} para torrent: {info_hash}[/green]",
    "[green]El demonio está en ejecución[/green] (PID: {pid})",
    "[green]Demonio reiniciado correctamente[/green]",
    "[green]Demonio detenido correctamente[/green]",
    "[green]Demonio detenido[/green]",
    "[green]Punto de control eliminado para {hash}[/green]",
    "[green]Punto de control eliminado para {info_hash}[/green]",
    "[green]Todos los archivos deseleccionados.[/green]",
    "[green]Todos los archivos deseleccionados[/green]",
    "[green]Deseleccionado(s) {count} archivo(s)[/green]",
    "[green]IP externa:[/green] {ip}",
    "[green]Forzado el inicio de {count} torrent(s)[/green]",
    "[green]Punto de control encontrado para: {torrent_name}[/green]",
    "[green]Verificación de integridad correcta: {count} piezas verificadas[/green]",
    "[green]Reglas de alerta cargadas desde {path}[/green]",
    "[green]Cargadas {count} reglas de alerta desde {path}[/green]",
    "[green]Configuración regional establecida en: {locale_code}[/green]",
    "[green]Enlace magnet añadido al demonio: {info_hash}[/green]",
    "[green]Movido a la posición {position}[/green]",
    "[green]¡La configuración de red parece óptima![/green]",
    "[green]No hay puntos de control con más de {days} días[/green]",
    "[green]¡Optimizaciones aplicadas correctamente![/green]\n[yellow]Nota: algunos cambios pueden requerir reinicio.[/yellow]",
    "[green]Optimizaciones guardadas en {path}[/green]",
    "[green]PEX actualizado para torrent: {info_hash}[/green]",
    "[green]Torrent pausado[/green]",
    "[green]Pausado(s) {count} torrent(s)[/green]",
    "[green]Los hooks de validación de pares están habilitados por configuración[/green]",
    "[green]Límite de velocidad por par para {peer_key}: {limit}[/green]",
    "[green]Límite por par establecido: {peer_key} = {upload} KiB/s[/green]",
    "[green]Realizando análisis básico de configuración...[/green]",
    "[green]Fijado:[/green] {cid}",
    "[green]Configuración del proxy guardada en {config_file}[/green]",
    "[green]Configuración del proxy actualizada correctamente[/green]",
    "[green]El proxy se ha desactivado[/green]",
    "[green]Regla de alerta {name} eliminada[/green]",
    "[green]Torrent quitado de la cola[/green]",
    "[green]Todas las opciones restablecidas para torrent {hash}[/green]",
    "[green]Restablecido {key} para torrent {hash}[/green]",
    "[green]Punto de control restaurado para: {name}[/green]\nHash de información: {hash}",
]

if __name__ == "__main__":
    keys = json.loads((ROOT / "dev/es_slice_3.json").read_text(encoding="utf-8"))
    if len(V) != len(keys):
        msg = f"count mismatch: V={len(V)} keys={len(keys)}"
        raise SystemExit(msg)
    OUT.write_text(json.dumps(V, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(OUT)
