#!/usr/bin/env python3
"""Fix MkDocs documentation link warnings by converting file references to proper formats."""

import re
import sys
from pathlib import Path
from typing import List, Tuple

# Repository URL from mkdocs.yml (update if needed)
REPO_URL = "https://github.com/yourusername/ccbittorrent"
REPO_BRANCH = "main"

# Patterns to match different link types
# Matches: [text](ccbt/path/to/file.py#L123) or [text](ccbt/path/to/file.py#L123-L145)
SOURCE_CODE_PATTERN = re.compile(
    r'\[([^\]]+)\]\((ccbt/[^)]+\.py(?:#[^)]+)?)\)'
)
# Matches: [text](ccbt.toml#L123) or [text](pyproject.toml#L123-L145) or [text](env.example)
CONFIG_FILE_PATTERN = re.compile(
    r'\[([^\]]+)\]\((ccbt\.toml(?:#[^)]+)?|pyproject\.toml(?:#[^)]+)?|env\.example(?:#[^)]+)?)\)'
)
# Matches: [text](dev/path/to/file.yaml)
DEV_FILE_PATTERN = re.compile(
    r'\[([^\]]+)\]\((dev/[^)]+)\)'
)
# Matches: [text](reports/...) - report links that might not exist
REPORT_PATTERN = re.compile(
    r'\[([^\]]+)\]\((reports/[^)]+)\)'
)


def convert_source_link(match: re.Match) -> str:
    """Convert source code file link to GitHub format."""
    link_text = match.group(1)
    file_path = match.group(2)
    
    # If it already has a line reference, preserve it
    if '#' in file_path:
        github_url = f"{REPO_URL}/blob/{REPO_BRANCH}/{file_path}"
    else:
        github_url = f"{REPO_URL}/blob/{REPO_BRANCH}/{file_path}"
    
    return f"[{link_text}]({github_url})"


def convert_config_link(match: re.Match) -> str:
    """Convert config file link to GitHub format."""
    link_text = match.group(1)
    file_path = match.group(2)
    
    github_url = f"{REPO_URL}/blob/{REPO_BRANCH}/{file_path}"
    return f"[{link_text}]({github_url})"


def convert_dev_link(match: re.Match) -> str:
    """Convert dev/ file link to GitHub format."""
    link_text = match.group(1)
    file_path = match.group(2)
    
    github_url = f"{REPO_URL}/blob/{REPO_BRANCH}/{file_path}"
    return f"[{link_text}]({github_url})"


def convert_report_link(match: re.Match) -> str:
    """Convert report link - keep as is if exists, otherwise convert to GitHub."""
    link_text = match.group(1)
    file_path = match.group(2)
    
    # For reports, we'll keep them as relative links since they should exist in docs/
    # But if they don't exist, we could convert to GitHub
    # For now, just keep them - they should be generated by build scripts
    return f"[{link_text}]({file_path})"


def fix_file_links(content: str) -> Tuple[str, int]:
    """Fix all problematic links in file content."""
    changes = 0
    
    # Fix source code links
    content, source_count = SOURCE_CODE_PATTERN.subn(convert_source_link, content)
    changes += source_count
    
    # Fix config file links
    content, config_count = CONFIG_FILE_PATTERN.subn(convert_config_link, content)
    changes += config_count
    
    # Fix dev/ file links
    content, dev_count = DEV_FILE_PATTERN.subn(convert_dev_link, content)
    changes += dev_count
    
    # Note: Report links are kept as-is since they should exist in docs structure
    
    return content, changes


def main():
    """Main function to fix documentation links."""
    docs_dir = Path(__file__).parent.parent.parent / "docs"
    
    if not docs_dir.exists():
        print(f"Error: docs directory not found at {docs_dir}")
        sys.exit(1)
    
    # Find all markdown files
    md_files = list(docs_dir.rglob("*.md"))
    
    total_changes = 0
    files_changed = 0
    
    for md_file in md_files:
        try:
            content = md_file.read_text(encoding="utf-8")
            new_content, changes = fix_file_links(content)
            
            if changes > 0:
                md_file.write_text(new_content, encoding="utf-8")
                files_changed += 1
                total_changes += changes
                print(f"Fixed {changes} links in {md_file.relative_to(docs_dir.parent)}")
        except Exception as e:
            print(f"Error processing {md_file}: {e}", file=sys.stderr)
            sys.exit(1)
    
    print(f"\nTotal: Fixed {total_changes} links in {files_changed} files")
    
    if total_changes == 0:
        print("No changes needed - all links are already in correct format")
        sys.exit(0)


if __name__ == "__main__":
    main()

